FROM python:3.12-slim

WORKDIR /app

# Install deps first so this layer is cached unless requirements.txt changes
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# COPY producer.py .
# CMD ["python3", "producer.py"]
COPY mock_producer.py .
CMD ["python3", "mock_producer.py"]